// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnw3nG2aciR6k_yd8mSP1xAbowNN5tNkQ',
    appId: '1:949370802248:web:1e95aae56abf13ab70487d',
    messagingSenderId: '949370802248',
    projectId: 'foodie-app-315bb',
    authDomain: 'foodie-app-315bb.firebaseapp.com',
    storageBucket: 'foodie-app-315bb.appspot.com',
    measurementId: 'G-NSTM4CP7TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmy3_edkeEliRGMaTIakyH71f3PXZbffQ',
    appId: '1:949370802248:android:df8274b7a22ec00a70487d',
    messagingSenderId: '949370802248',
    projectId: 'foodie-app-315bb',
    storageBucket: 'foodie-app-315bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDletZLKDo8Zl-gJ2PQxRZWnmgInLOyQTo',
    appId: '1:949370802248:ios:179475c30f1103e170487d',
    messagingSenderId: '949370802248',
    projectId: 'foodie-app-315bb',
    storageBucket: 'foodie-app-315bb.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDletZLKDo8Zl-gJ2PQxRZWnmgInLOyQTo',
    appId: '1:949370802248:ios:179475c30f1103e170487d',
    messagingSenderId: '949370802248',
    projectId: 'foodie-app-315bb',
    storageBucket: 'foodie-app-315bb.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnw3nG2aciR6k_yd8mSP1xAbowNN5tNkQ',
    appId: '1:949370802248:web:a764a7b3c7c80e8d70487d',
    messagingSenderId: '949370802248',
    projectId: 'foodie-app-315bb',
    authDomain: 'foodie-app-315bb.firebaseapp.com',
    storageBucket: 'foodie-app-315bb.appspot.com',
    measurementId: 'G-N2R6PYLR2G',
  );
}
